version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:756418066335:task-definition/swiggy-task:1"
        LoadBalancerInfo:
          ContainerName: "swiggy"
          ContainerPort: 3000
