steps:

# Install Node Dependencies
- name: 'node:18'
  entrypoint: 'npm'
  args: ['install']

# SonarQube Scan
- name: 'sonarsource/sonar-scanner-cli:latest'
  entrypoint: 'sh'
  secretEnv:
    - SONAR_TOKEN
  args:
    - '-c'
    - |
      echo "Using Sonar host: $_SONAR_HOST"

      if [ -z "$_SONAR_HOST" ]; then
        echo "ERROR: _SONAR_HOST substitution variable is empty"
        exit 1
      fi
      
      sonar-scanner \
      -Dsonar.projectKey=swiggy-clone \
      -Dsonar.sources=. \
      -Dsonar.host.url=$_SONAR_HOST \
      -Dsonar.token=$$SONAR_TOKEN

# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/smitha-artifact-repo/swiggy-clone:$SHORT_SHA'
    - '.'

# Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/smitha-artifact-repo/swiggy-clone:$SHORT_SHA'

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - smitha-swiggy-service
    - --image
    - asia-south1-docker.pkg.dev/$PROJECT_ID/smitha-artifact-repo/swiggy-clone:$SHORT_SHA
    - --region
    - asia-south1
    - --platform
    - managed
    - --allow-unauthenticated

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/smitha-swiggy-sonar-token/versions/latest
      env: SONAR_TOKEN

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/smitha-artifact-repo/swiggy-clone:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
